### ISSUE TITLE
Kanban.ListWorkloadsByUser is broken after upgrading to NetCore 1.1

### ISSUE THREAD

**Issue by fcatae** [DXBrazil/Arda#21]
Exception:
```
Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory[1]
      An exception occurred in the database while iterating the results of a query.
      System.InvalidOperationException: Sequence contains no elements
         at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
         at lambda_method(Closure , ValueBuffer )
         at System.Linq.Enumerable.<JoinIterator>d__80`4.MoveNext()
         at System.Linq.Enumerable.<JoinIterator>d__80`4.MoveNext()
         at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
         at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at lambda_method(Closure , ValueBuffer )
   at System.Linq.Enumerable.<JoinIterator>d__80`4.MoveNext()
   at System.Linq.Enumerable.<JoinIterator>d__80`4.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
```

**Comment by fcatae** [comment]
The corresponding command with error:
```
from wb in _context.WorkloadBacklogs 
join wbu in _context.WorkloadBacklogUsers on wb.WBID equals wbu.WorkloadBacklogWBID
join uk in _context.Users on wbu.User.UniqueName equals uk.UniqueName
where uk.UniqueName.Equals(uniqueName)
orderby wb.WBTitle
select new WorkloadsByUserViewModel
{
}
```
The problem seems to be related to the join of WorkloadBacklogs and WorkloadBacklogUsers tables. The initial join uses a complicated relation of

```
wb.WBUsers.Where(u => u.User.UniqueName == uniqueName).First().WBUserID equals wbu.WBUserID
```

I think it should be something like this:

```
on wb.WBID equals wbu.WorkloadBacklogWBID
```
