### ISSUE TITLE
Visual Studio 2017 migration broke integration tests

### ISSUE THREAD

**Issue by fcatae** [DXBrazil/Arda#54]
Visual Studio 2017 migration broke integration tests - it causes problem in Entity Framework
```
Error Message:
 System.InvalidOperationException : No value provided for required parameter '_outer_WBID'.
Stack Trace:
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.CreateCommand(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state)

   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Arda.Kanban.Repositories.WorkloadRepository.GetWorkloadsByUser(String uniqueName) in C:\src\Arda\src\Arda.Kanban\Repositories\WorkloadRepository.cs:line 327
   at IntegrationTests.Workload.<>c__DisplayClass5_0.<Workload_GetWorkloadsByUser>b__0(WorkloadViewModel[] list, KanbanContext ctx) in C:\src\Arda\test\IntegrationTests.Arda.Kanban.Repositories\Repositories\Workload.cs:line 112
   at IntegrationTests.ArdaTestMgr.Validate[R](ISupportSnapshot`1 testClass, String testName, Func`3 testFunction, String member) in C:\src\Arda\test\IntegrationTests.Arda.Kanban.Repositories\ArdaTestManager\ArdaTestMgr.cs:line 92
   at IntegrationTests.Workload.Workload_GetWorkloadsByUser() in C:\src\Arda\test\IntegrationTests.Arda.Kanban.Repositories\Repositories\Workload.cs:line 108
```

**Comment by fcatae** [comment]
Cause: project was migrated to EF 1.1.1, and it raise the exception. 
Solution: rollback to EF 1.1.0
